--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/SimplePets
build-by-default: true
branches:
- master

projects:
  SimplePets:
    icon: "/assets/logo-min.png"
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.1.0
      - src: muqsit/InvMenu/InvMenu
        version: ^4.4.1
        branch: "4.0"
      - src: brokiem-pm-pl/EasyUI/libEasyUI
        version: 3.0.0
...
