name: SimplePets
main: brokiem\simplepets\SimplePets
version: 2.0.0-beta+dev
api: 5.0.0
authors: [ "broki", "brokiem", "broski" ]

website: https://github.com/brokiem/SimplePets

extensions:
  Core: '>=8.0'

permissions:
  simplepets.ui:
    default: op
  simplepets.spawn:
    default: op
  simplepets.remove:
    default: op
  simplepets.inv:
    default: true
  simplepets.ride:
    default: true
  simplepets.petlist:
    default: op
